os: Visual Studio 2015

environment:
  image: Visual Studio 2017
  SignClientSecret:
    secure: 2QKIbnEaxM/df01+GLvTjVKdLL7RlwKmCR/APcWFRUUF2VQWBRQFQ1DP3gK49epL

install:
  # Download .NET CLI 1.1.1
  - ps: $url = "https://go.microsoft.com/fwlink/?linkid=843454"

   # Download .NET Core SDK and add to PATH
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - ps: nuget install -ExcludeVersion SignClient -Version 0.5.0-beta4 -pre -OutputDirectory .\build\

build_script:
  - ps: gitversion /output buildserver
  - ps: .\build\Update-Version.ps1 $env:GitVersion_NuGetVersion
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build /p:Configuration=Release .\DocumentFormat.OpenXml.Tests

after_build:
  - ps: dotnet pack .\DocumentFormat.OpenXml -c Release  -o ..
  - ps: .\build\SignPackage.ps1

test_script:
  - cmd: dotnet test /p:Configuration=Release .\DocumentFormat.OpenXml.Tests\DocumentFormat.OpenXml.Tests.csproj

deploy:
  provider: NuGet
  server: https://dotnet.myget.org/F/open-xml-sdk/api/v2/package
  api_key:
    secure: +uagaLcg+y8G8ZBxlXm0E5VmTHeT030NeoyHZGU8V7MtIPc1+VUXru0mAPVh0KhK
  on:
    branch: [master, vNext, Office2016]
